#!/bin/ruby

require 'socket'
require 'erb'

SCRIPT_DIR = File.dirname(__FILE__)

$stdout.sync = true

def create_node(name, image='agent', sign_cert=true, run_puppet=true)
  puts "Creating #{name}..."
  `puppet apply -e "dockeragent::node { '#{name}': ensure => present, image => '#{image}', require_dockeragent => false, }"`
  wait_for_container(name)
  if sign_cert
    `puppet cert generate #{name}`
    sleep 2
    `cp -f /etc/puppetlabs/puppet/ssl/certs/#{name}.pem /etc/docker/ssl_dir/`
    `cp -f /etc/puppetlabs/puppet/ssl/public_keys/#{name}.pem /etc/docker/ssl_dir/public_keys/`
    `cp -f /etc/puppetlabs/puppet/ssl/private_keys/#{name}.pem /etc/docker/ssl_dir/private_keys/`
  end
end

def run_puppet_on_nodes
  docker_hosts.each do |name, ip|
    #Use a bogus tag to only run pluginsync
    `docker exec -d #{name} puppet agent -t --tags bogus`
  end
end

def wait_for_container(name)
  count = 0
  while !system("docker ps | grep #{name}") && count < 10 do
    count =+ 1
    sleep 2
  end
end

def docker_hosts
  hosts = {}
  containers = `docker ps`.split("\n")
  containers.shift
  containers.each do |line|
    name = line.split.last
    hosts[name] = `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' #{name}`.chomp
  end
  return hosts
end

def clear_nodes
  hosts = docker_hosts
  hosts.each do |name, ip|
    `systemctl stop docker-#{name}.service`
    `/bin/find /etc/docker/ssl_dir -name #{name}.pem -delete`
    `/opt/puppetlabs/bin/puppet cert clean #{name}`
  end
end

def update_docker_hosts
  hosts = docker_hosts
  fqdn = `facter fqdn`.chomp
hosts_template = <<-HEREDOC
127.0.0.1 <%= fqdn %> learning localhost localhost.localdomain localhost4
::2 localhost localhost.localdomain localhost6 localhost6.localdomain6
<% hosts.each do |name, ip|  %>
<%= $ip %> <%= $hostname %>\n
<% end %>
HEREDOC
  puts 'Updating /etc/hosts...'
  File.write('/etc/hosts', ERB.new(hosts_template, 3, '>').result(binding))
end

def wait_for_ssh
  puts "Waiting for node SSH services to become available..."
  docker_hosts.each do |name, ip|
    retries = 0
    begin
      Socket.tcp(name, 22, connect_timeout: 5)
    rescue
      retries +=1
      if retries > 10
        puts "Timed out waiting for node SSH services to become available. Please refer the the Learning VM troubleshooting guide."
        exit 1
      end
      retry
    end
  end
end

def node_setup(quest)
  run_puppet_after = true
  case quest
  when 'hello_puppet'
    create_node('hello.puppet.vm', image='no_agent', sign_cert=false, run_puppet=false)
    run_puppet_after = false
  when 'agent_run'
    create_node('agent.puppet.vm', image='agent', sign_cert=false, run_puppet=false)
    run_puppet_after = false
  when 'manifests_and_classes'
    create_node('cowsay.puppet.vm')
  when 'package_file_service'
    create_node('pasture.puppet.vm')
  when 'variables_and_templates'
    create_node('pasture.puppet.vm')
  when 'class_parameters'
    create_node('pasture.puppet.vm')
  when 'facts'
    create_node('pasture.puppet.vm')
  when 'conditional_statements'
    create_node('pasture-dev.puppet.vm')
    create_node('pasture-prod.puppet.vm')
  when 'the_forge'
    create_node('pasture-db.puppet.vm')
    create_node('pasture-app.puppet.vm')
  when 'roles_and_profiles'
    create_node('pasture-app-small.puppet.vm')
    create_node('pasture-app-large.puppet.vm')
    create_node('pasture-db.puppet.vm')
  when 'defined_resource_types'
    create_node('pasture-app-small.puppet.vm')
    update_docker_hosts
  when 'application_orchestrator'
    create_node('pasture-app-large.puppet.vm')
    create_node('pasture-db.puppet.vm')
  end
  update_docker_hosts
  run_puppet_on_nodes if run_puppet_after
  wait_for_ssh
end

clear_nodes
node_setup(ARGV[0])
